JIRA-97 #DOCS #comment 'PR workflow reviewer api 요청 결과에 맞게 fail하도록 변경'

diff --git a/.github/workflows/pr_workflow.yaml b/.github/workflows/pr_workflow.yaml
--- a/.github/workflows/pr_workflow.yaml
+++ b/.github/workflows/pr_workflow.yaml
@@ -44,10 +44,18 @@ jobs:
 
       - name: Use GitHub API to set reviewers
         run: |
-          REVIEWER_JSON=$(echo "${REVIEWERS[@]}" | jq -R -c -s 'split(" ")')
-          curl \
+          RESPONSE_CODE=$(curl \
+            -o /dev/null \
+            -s -w "%{http_code}" \
             -X POST \
             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/UOS-CSDESIGN/Epimetheus/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
-            -d '{"reviewers":${{ env.REVIEWERS }}}'
+            -d '{"reviewers":${{ env.REVIEWERS }}}')
+
+          if [ "$RESPONSE_CODE" -ne 201 ]; then
+            echo "Failed to set reviewers. Response code: $RESPONSE_CODE"
+            exit 1
+          fi
+      
+      
